# Generated by Django 3.2.3 on 2021-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('d', 'Draft'), ('p', 'Publish')], default='d'),
        ),
    ]
